class Data {
  static String termsAndConditions = '''Terms of Use
These Terms of Use, together with the privacy policy available at www.projectbuddy.com/privacy ("Privacy Policy") and the rules, policies, terms and conditions set forth in, referred to and/or linked herein, all of which are incorporated herein by reference, are, collectively, the "Agreement".
This Agreement constitutes a legal agreement between you ("you" or "User") and PGN Design Group, Inc. d/b/a Project Buddy ("PB" or "us"). This Agreement governs your use of our services and platform that facilitates communications between Users offered through our website located at www.projectbuddyservices.com, as it may be modified, relocated and/or redirected from time to time (the "Site"), and the mobile applications offered by us (the "Apps"). Our services, platform, Site and Apps are collectively referred to as the "Project Buddy Platform".
By using or registering with the Project Buddy Platform or any portions thereof, you hereby expressly acknowledge and agree to be bound by the terms and conditions of this Agreement, and any future amendments and additions to this Agreement as we may publish from time to time. Please read this Agreement carefully. If you do not agree to be bound by this Agreement, you will not have any right to use the Project Buddy Platform. PB's acceptance is expressly conditioned upon your assent to this Agreement in its entirety. If this Agreement is considered to be an offer by us, acceptance is expressly limited to this Agreement.
By using the Project Buddy Platform, you represent and warrant that: (i) you are at least 18 years old, are at least of the legally required age in the jurisdiction in which you reside, and are otherwise capable of entering into binding contracts; and (ii) you have the right, authority and capacity to enter into this Agreement and to abide by the terms and conditions of this Agreement, and that you will so abide. Where you enter into this Agreement on behalf of a company or other organization, you represent and warrant that you have authority to act on behalf of that entity and to bind that entity to this Agreement.
To the extent permitted and except where prohibited by applicable law, these Terms of Use include:
• Your agreement that the Project Buddy Platform is provided "as is" and without warranty (Section 15).
• Your agreement that the Project Buddy Platform is solely a communications platform providing a method for Professional Services to be booked, that all Professional Services are performed by third parties, and that PB has no liability for any Professional Services or any acts or omissions of third parties (Sections 1 and 15), with the exception of PB’s Money-Back Guarantee (Section 3(d)).
• Your agreement that PB's Money-Back Guarantee is limited to Payments paid by Requesters through the Project Buddy Platform (Section 3(d)).
• Your agreement to release Project Buddy from liability based on claims relating to Services and otherwise (Section 15) and your agreement to the limitation of time within which a claim can be brought (Section 20).
• Your agreement to indemnify Project Buddy from claims due to your use, misuse or inability to use the Project Buddy Platform, the Merchandise and/or Professional Services, your violation of this Agreement, applicable laws or third party rights, and/or content or information submitted from your account to the Project Buddy Platform (Section 16).
• Your agreement that either party may compel binding arbitration for most types of disputes, and your agreement to submit to an informal dispute resolution process for at least 30 days prior to the initiation of any claim (Section 17).
• Your agreement that no claims can be adjudicated on a class basis (Section 17).
• Your consent to any modifications or amendments to this Agreement (Section 21).
• Your consent to the collection, use, sharing and transfer of your data as outlined in the Privacy Policy as updated from time to time.
1. The Project Buddy Platform is Solely a Venue for Communications; Background Checks.
a. The Project Buddy Platform is Solely a Venue for Communications. The Project Buddy Platform is a communications platform for enabling the connection between individuals seeking to obtain services ("Requesters") and/or individuals seeking to provide services ("Professionals"). Requesters and Professionals together are referred to as "Users". Those certain services requested by the Requesters, which are to be completed by the Professionals, are hereinafter referred to as "Professional Services". The Professional Services may include the weekly project managing of a particular project. Project Buddy does not itself provide Professional Services or Merchandise. The provision of all Professional Services is up to the Professionals, which may be scheduled through use of the Project Buddy Platform. PROJECT BUDDY, THROUGH THE PROJECT BUDDY PLATFORM, OFFERS INFORMATION AND A METHOD TO OBTAIN SUCH PROFESSIONAL SERVICES AND/OR MERCHANDISE, BUT DOES NOT AND DOES NOT INTEND TO PROVIDE SUCH PROFESSIONAL SERVICES OR MERCHANDISE ITSELF OR ACT IN ANY WAY AS A RETAILER OR MANUFACTURER, OR AS A CONTRACTOR, HANDYMAN, OR OTHER HOME-RELATED OR CONSTRUCTION-RELATED SERVICE PROVIDER, AND HAS NO RESPONSIBILITY OR LIABILITY FOR ANY PROFESSIONAL SERVICES AND/OR MERCHANDISE PROVIDED TO THE REQUESTER BY PROFESSIONALS, INCLUDING, BUT NOT LIMITED TO, A WARRANTY OR CONDITION OF GOOD AND WORKMANLIKE SERVICES, WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE OR COMPLIANCE WITH ANY LAW, REGULATION, OR CODE. PROJECT BUDDY IS NOT AFFILIATED WITH, ENDORSED OR SPONSORED BY ANY THIRD PARTY MERCHANDISE PROVIDER OR RETAILER.
b. Background Checks. Project Buddy checks the backgrounds of Professionals via third party background check services. However, each Requester should exercise caution and common sense to protect its personal safety and property, just as you would when interacting with any person whom you do not know. BY USING THE PROJECT BUDDY PLATFORM, THE REQUESTER AGREES TO HOLD PROJECT BUDDY FREE FROM THE RESPONSIBILITY FOR ANY LIABILITY OR DAMAGE THAT MIGHT ARISE OUT OF THE PROFESSIONAL SERVICES. PROJECT BUDDY IS NOT RESPONSIBLE FOR THE CONDUCT, WHETHER ONLINE OR OFFLINE, OF ANY USER INCLUDING PROFESSIONALS, AND WILL NOT BE LIABLE FOR ANY CLAIM, INJURY OR DAMAGE ARISING IN CONNECTION WITH ANY PROFESSIONAL SERVICES.
2. Personal Information; User Accounts.
a. Collection of your Personal Information. Some of the materials available on the Project Buddy Platform may require prior registration to access. If you decide to access such materials you will be required to register. We may refuse to grant you, and you may not use, a user name, email address or screen name that is already being used by someone else; that may be construed as impersonating another person; that belongs to another person; that violates the intellectual property or other rights of any person; that is offensive; or that we reject for any other reason in our sole discretion. When you complete a registration with us, you will be required to provide certain personal information. You agree that such information will be true, accurate and complete, and that you will update this information promptly when it changes. If you provide any information that is untrue or inaccurate, not current, or incomplete, or if we suspect that your information is untrue or inaccurate, not current, or incomplete, we may, in our sole discretion, suspend or terminate your right to access any material for which registration is required. Any personally identifiable information supplied hereunder will be subject to the terms of the Privacy Policy.
b. Account, Password and Security. You are the sole authorized user of your account. You are responsible for maintaining the confidentiality of any username, password and account provided by you or us for accessing the Project Buddy Platform. You are solely and fully responsible for all activities that occur under your password or account, except that Project Buddy may, in certain circumstances, access your account to make changes that you request, such as rescheduling a Service appointment. Project Buddy has no control over the use of any User's account by the User or third parties and expressly disclaims any liability derived therefrom. Should you suspect that any unauthorized party may be using your password or account or you suspect any other breach of security, you must contact us immediately at projectbuddyservices.com/help. Nothing in this section shall affect PB's rights to limit or terminate the use of the Project Buddy Platform, as provided below in section 4(b).
c. Proof of Identity. You will provide us with such proof of identity as we may reasonably request from time to time.
d. Text Messages and Phone Calls. By providing your phone number and using the Project Buddy Platform, we may, to the extent permitted by applicable law, use your mobile phone number for calls and, if such phone number is a mobile number, for text (SMS) messages, in order to assist with facilitating the requested Professional Services. Standard call or message charges or other charges from your phone carrier may apply to calls or text (SMS) messages we send you. You may opt-out of receiving text (SMS) messages from us by replying with the word "STOP" to a text message from us. You acknowledge that opting out of text (SMS) messages may impact your ability to use the Project Buddy Platform.
e. Emails. Project Buddy may send you confirmation and other transactional emails regarding the Professional Services. Project Buddy may also send you emails about services that we think might interest you ("Promotional Emails"). You can unsubscribe from Promotional Emails at any time by clicking unsubscribe in our email communications or contacting us.
3. Payments; Money Back Guarantee; Claims.
a. Payments. Users of the Project Buddy Platform contract for Professional Services directly with other Users. Project Buddy is not a party to any contracts for Professional Services. The Project Buddy Platform facilitates these contracts by supplying a medium through which Requesters can connect with Professionals, schedule Professional Services, and make payments for Professional Services ("Payments"). Requesters are obligated to pay in advance for the Professional Services and/or Merchandise they order through the Project Buddy Platform. We will charge the Requester's credit card according to the amount the Requester has agreed to on the Project Buddy Platform with respect to all Professional Services and/or Merchandise, the Requester has ordered, and for all purchases and payments for reimbursement costs, fees or expenses associated with a Professional Service, and the Requester hereby authorizes us to charge the credit card on file in the Requester's Project Buddy Platform account for such amounts. We will use third party services to process credit card information. We retain the right, in our sole discretion, to place a hold on the Requester's credit card for an ordered or completed Professional Service transaction. Seventy-two (72) hours after a Professional Service is completed, if there is no complaint by the Requester, we will mark the Professional Service as closed. If the Requester has agreed with the Professional to extend or reduce the hours in or to reschedule a requested Professional Service, the Requester bears the responsibility for notifying Project Buddy. Requesters must notify Project Buddy either by changing the date or hours of the requested Professional Service through the Project Buddy Platform or by visiting the Project Buddy Help Center. All Payments by Requesters must be made through the Project Buddy Platform. Any Payments paid outside of the Project Buddy Platform are not subject to our Money-Back Guarantee in Section 3(d). Except for the Money-Back Guarantee in Section 3(d), and the Refund Policy in Section 3(e), no refunds or credits will be provided once the Requester's credit card has been charged, except that at our sole discretion, refunds or credits may be granted in extenuating circumstances, as a result of specific promotions, or to correct any errors we have made. While we will use commercially reasonable efforts to ensure the security of all credit card and all other personal information, we expressly disclaim any liability for any damage that may result should any information be released to any third parties, and you agree to hold us harmless for any damages that may result therefrom. Requesters will be liable for all transaction taxes on the Professional Service(s) provided (other than taxes based on PB's income).
b. Job Rate. The rate per week for a Professional Service ("Job Rate") depends on factors, such as location and how frequently a Recurrent Service is ordered. Therefore, the same Professional Service may cost more in a different location or if the Professional Service is ordered less frequently.
c. Recurrent Service. When requesting a Professional Service, Requesters may have the option of choosing that the Professional Service be repeated on a regular basis ("Recurrent Service"). For example, a Requester may choose that a Project Buddy professional manage a six week project for it’s duration. When a Requester chooses a Recurrent Service, Project Buddy will automatically schedule that Recurrent Service to occur on future dates indefinitely at the frequency requested by Requester. Requester's credit card will be charged for the Recurrent Service as the Professional Service appointments occur and for any applicable cancellation fees. Project Buddy cannot guarantee that the same Professional will be scheduled for each Recurrent Service appointment or that Recurrent Service appointments will not be canceled.
d. Money-Back Guarantee. If the Requester ordered and paid for a Professional Service through the Project Buddy Platform and the Professional Service has already been performed, and if the Requester is not satisfied with that Professional Service, then the Requester is eligible for our Money-Back Guarantee provided that the Requester reports the issue within seventy-two (72) hours of the Professional Service appointment to our customer service telephone number by visiting the Project Buddy Help Center. The Money-Back Guarantee is as follows: we will either refund the Requester's Payment amount for such Professional Service, or, alternatively, we will have the applicable Professional Service re-performed. If the Requester elects to have the Professional Service re-performed and the Requester is still not satisfied with the Professional Service after it has been re-performed, we will refund the Requester's Payment amount for such Professional Service. The amount of PB's Money-Back Guarantee is limited to any Payment the Requestor made for the Professional Service. PB's Money-Back Guarantee does not apply to any other cost, liability, damage, injury, or claim arising from or in connection with the Professional Services. For clarity, PB’s Money-Back Guarantee does not apply to any payments made for Merchandise, and solely applies to payments made for the Professional Services as applicable.
e. Project Buddy Delivery Refund Policy.
i. If you decide that you do not want the Merchandise before it has been unpacked or opened, or if the Merchandise you ordered does not fit into your home or your building refuses entry, Project Buddy will return the Merchandise and refund you the cost of the Merchandise (provided, however, that Project Buddy shall not refund the cost of the Professional Services).
ii. If any Merchandise is broken in the course of performing the Professional Services, Project Buddy will remove and replace the broken Merchandise (or, where applicable, the broken component of the Merchandise) and re-perform the applicable Professional Services at no additional cost to you (provided, however, that Project Buddy shall not refund the cost of the Merchandise or refund the cost of the Professional Services, except as set forth in 3(d) above).
iii. If you wish to return any Merchandise once it has been unpacked or 
opened, Project Buddy will remove and return the Merchandise for a fee of One
 Hundred Dollars (\$100.00) per item. If Project Buddy is able to obtain a 
 refund from the third party Merchandise provider using commercially reasonable efforts, Project Buddy will credit you the amount of such refund. Project Buddy shall not be responsible for any payment to you if it is unable to obtain a refund for the Merchandise using commercially reasonable efforts.
4. Term and Termination; Cancellation of Professional Services; Survival.
a. Term. This Agreement shall continue in full force and effect until such time as it is terminated by you or by us.
b. Termination by Project Buddy. We may terminate this Agreement or terminate or suspend your right to use the Project Buddy Platform at any time for any or no reason (including, without limitation, in the event that we believe that you have breached this Agreement or any policy posted on the Project Buddy Platform, or if we otherwise find that you have engaged in inappropriate and/or offensive behavior (collectively, "Prohibited Conduct")) by providing you with written or email notice of such termination to the physical or email address you have provided us, and termination will be effective immediately upon such notice. Except in the event that we terminate or suspend your right to use the Project Buddy Platform due to any Prohibited Conduct, we will refund in full any payments for Project Buddy services or Professional Services that have not been performed or completed. If we terminate or suspend your account for any reason, you are prohibited from registering and creating a new account under your name, a fake or borrowed name, or the name of any third party, even if you may be acting on behalf of the third party. In addition to terminating or suspending your account, we reserve the right to take appropriate legal action, including without limitation pursuing civil, criminal, and injunctive redress. When terminating your account, Project Buddy may delete the account and all the information in it. You have no ownership rights to your account.
c. Termination by You. You may terminate this Agreement by completely and permanently ceasing to use the Project Buddy Platform (provided that there are no outstanding Professional Services ordered under your password or account) and by closing any account you have opened on the Project Buddy Platform. If you attempt to terminate this Agreement while there are still outstanding Professional Services ordered under your password or account, this Agreement shall not terminate until such Professional Services have been performed or otherwise canceled as permitted by Project Buddy.
d. Policy for Service Cancellation by Requester. PB's cancellation policy for
e. Policy for Service Cancellation by Professional. When a Professional cancels a scheduled Professional Service appointment, the Project Buddy Platform generally notifies the Requester and makes the Requester's Professional Service request available for another Professional to select. However, Project Buddy cannot guarantee that a canceled Professional Service appointment will be selected by another Professional and rescheduled or that the Professional Service request will be completed. Professionals who cancel a scheduled Professional Service appointment may incur fees as provided in the Service Agreement.
f. Survival. All provisions that should by their nature survive the expiration or termination of this Agreement, including without limitation, Sections 8, 10 and 14-22, shall so survive.
5. Links to and Plug-Ins from Other Web Sites or Media. Links (such as hyperlinks) from the Project Buddy Platform to and plug-ins from sites or applications owned, operated or controlled by third parties (collectively, "Third Party Sites") do not constitute the endorsement by Project Buddy of the Third Party Sites or their content. Such links and plug-ins are provided as an information service, for reference and convenience only. Project Buddy does not control any Third Party Sites, and is not responsible for their content. It is your responsibility to evaluate the content and usefulness of the information obtained from Third Party Sites. The use of any Third Party Site is governed by the terms and conditions of use and privacy policy of that Third Party Site. YOU ACCESS THIRD PARTY SITES AT YOUR OWN RISK. PROJECT BUDDY EXPRESSLY DISCLAIMS ANY LIABILITY ARISING IN CONNECTION WITH YOUR USE AND/OR VIEWING OF ANY THIRD PARTY SITES, AND YOU HEREBY AGREE TO HOLD PROJECT BUDDY HARMLESS FROM ANY LIABILITY THAT MAY RESULT FROM THIRD PARTY SITES.
6. Community Areas. The Project Buddy Platform may contain blogs, message boards, applications, reviews, job postings, chat areas, news groups, forums, communities and/or other message or communication facilities that allow Users to communicate with other Users (collectively, "Community Areas"). All submissions made to Community Areas within the Project buddy Platform will be public, and we will not be responsible for any information or materials posted in Community Areas. You may only use such Community Areas to send and receive messages and material that are relevant and proper to the applicable forum and that comply with this Agreement. "Your Information" is defined as any information and materials you provide to us or other Users in connection with your registration for and use of the Project Buddy Platform, including without limitation, information and materials that are posted or transmitted for use in Community Areas. You are solely responsible for Your Information, and we are merely a passive conduit for your online distribution and publication of Your Information. You hereby represent and warrant that Your Information: (a) will comply at all times with this Agreement, including but not limited to Section 7 (Rules for Use of the Project Buddy Platform) below, and with Section 2 (Personal Information; User Accounts) above; and (b) will not create liability for us or cause us to lose (in whole or in part) the services of our Internet Service Providers (ISPs), customers, or other partners or suppliers. You hereby grant us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sublicensable (through multiple tiers) right to use, host, store, reproduce, modify, create derivative works, communicate, publish, publicly perform, publicly display and distribute all of Your Information that is posted to Community Areas from or through your account on the Project Buddy Platform, including but not limited to all images, videos, musical works and text included in such postings. The rights you grant in this license are for the limited purpose of operating, promoting, and improving the Project Buddy Platform. We reserve the right to remove postings from Community Areas in our sole discretion.
7. Rules for Use of the Project Buddy Platform. During the term of this Agreement, Requesters may use the Project Buddy Platform for your personal use only (or for the use of a person, including a company or other organization that you validly represent). Requesters may use the Project Buddy Platform to book Professional Services solely with respect to a location where the Requester is legally authorized to have Professional Services performed. Requesters may not use the Project Buddy Platform for any other purposes or in connection with any commercial endeavors whatsoever without our express prior written consent. Requesters agree that an order for Professional Services is an offer, which is only accepted when the Requester receives a confirmation of the order. Requesters agree to treat Professionals courteously and lawfully, to provide a safe and appropriate working environment for them that is in compliance with all applicable laws and regulations, and to provide reasonable co-operation to Professionals to enable them to supply Professional Services. Requesters agree to communicate any complaints to us and not to the Professionals. Requesters agree to comply with our complaint and other policies designated on the Site. Requesters acknowledge that their selected Professional may be unavailable from time to time, e.g. due to illness, vacation or leaving Project Buddy. Professionals agree to provide Professional Services in accordance with all applicable laws and regulations and with the Service Agreement. You shall NOT use the Project Buddy Platform (including but not limited to any Community Areas) to do any of the following:
a. Upload files that contain viruses, Trojan horses, corrupted files, or any other similar software that may damage the operation of another's computer.
b. Upload files that contain software or other material that violates the intellectual property rights or rights of privacy or publicity of any third party.
c. Defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as, but not limited to, rights of privacy and publicity) of others, including but not limited to our staff and other Users.
d. Post a review or rating unless such review or rating contains your independent, honest, genuine opinion.
e. Use the Project Buddy Platform or any Professional Service for any purpose or in any manner that is in violation of local, state, national, or international law.
f. Publish, post, upload, distribute or disseminate any profane, defamatory, false, misleading, fraudulent, threatening or unlawful topics, names, materials or information, or any materials, information or content that involve the sale of counterfeit or stolen items.
g. Advertise or offer to sell any goods or services for any commercial purpose or solicit employment or contract work which is not relevant to services offered through the Project Buddy Platform. You may not solicit, advertise for, or contact in any form Users for employment, contracting, or any other purpose not related to Professional Services facilitated through the Project Buddy Platform without express written permission from us.
h. Use the Project Buddy Platform to collect usernames and/or email addresses of members by electronic or other means without our express prior written consent.
i. Conduct or forward surveys, contests, pyramid schemes, or chain letters.
j. Impersonate another person or allow any other person or entity to use your identification to post or view comments or otherwise use your account.
k. Post the same note repeatedly (referred to as 'spamming'). Spamming is strictly prohibited.
l. Download any file posted by another User that you know, or reasonably should know, cannot be legally distributed through the Project Buddy Platform, or post or upload any content to which you have not obtained any necessary rights or permissions to use accordingly.
m. Restrict or inhibit any other User from using and enjoying the Project Buddy Platform.
n. Imply or state that any statements you make are endorsed by us, without our prior written consent.
o. Reverse engineer, disassemble, decompile, translate, modify, adapt, license, sublicense, alter, copy, distribute, hack or interfere with the Handy Platform, its servers or any connected networks, use a robot, spider, manual and/or automatic processes or devices to data-mine, data-crawl, scrape or index the Project Buddy Platform in any manner, or attempt to do any of the foregoing.
p. Remove or alter, visually or otherwise, any copyrights, trademarks or proprietary marks and rights owned by us.
q. Upload content that is offensive and/or harmful, including, but not limited to, content that advocates, endorses, condones or promotes racism, bigotry, hatred or physical harm of any kind against any individual or group of individuals.
r. Upload content that provides materials or access to materials that are obscene, adult or sexual or that exploit anyone, and in particular people under the age of 18, in an abusive, violent or sexual manner.
s. Register to use the Project Buddy Platform under different usernames or identities, after your account has been suspended or terminated.
t. Mirror or archive any part of the Project Buddy Platform or any content or material contained on the Project Buddy Platform without PB's written permission.
8. No Employment. Project Buddy provides a software platform which allows you to connect with independent Professionals. Project Buddy is not the employer of any Professional. You acknowledge that we do not supervise, direct, or control a Professional’s work or Professional Services performed in any manner. A Professional provides services to you as an independent contractor, and is not an employee, joint venture, partner, agent, or franchisee of Project Buddy for any purpose whatsoever.
9. Special Promotions; Gift Cards and Vouchers.
a. Changes to Promotions. We may from time to time provide certain promotional opportunities to Requesters. All promotions will be run at our sole discretion, and can be activated, modified or removed at any time by us without advance notification.
b. Referral Credits. In the event that you are given a code through which you may refer a friend to the Project Buddy Platform in exchange for a referral credit, you shall not use any online marketing or advertising to promote such code or to artificially increase the amount of credits awarded. By way of example, you may not post, or cause, request or permit a third party to post any such code on a coupon website, nor use any paid search marketing, online advertising, forum posting, newsgroup posting or bulk email to disseminate such code. You may only share such code with your personal friends and acquaintances for legitimate referral purposes, as determined by us in our sole discretion. Without limiting our other rights and remedies, we may terminate such code and/or your account for any breach of this Section. For questions or additional information, contact us at projectbuddyservices.com/help.
c. Gift Cards and Vouchers. Project Buddy gift cards ("Gift Cards") and vouchers or promotional codes for special offers or discounts ("Vouchers") (individually, “Card", or together, "Cards") may be available and can be used to pay in part or in full for Professional Services. Card must be presented at the time of purchase and available balance will be applied to your purchase. Card does not expire and there are no fees associated with use of Card.
d. You agree that you will only use one Voucher per person and will use Vouchers only for your first Professional Service. You agree that you will comply with all Voucher and Gift Card terms. Cards are not replaceable if lost or stolen, and cannot be combined with any other Gift Cards, Vouchers, gift certificates, or other coupons. Cards cannot be used for previous purchases, credits, or the purchase of gift cards, and cannot be used to make a payment towards third party items the balance on a credit card. We reserve the right to limit quantities of Gift Cards purchased by any person or entity and to cancel a Gift Card if we believe that the Gift Card was obtained through fraudulent or unauthorized means. No credit card, credit line, overdraft protection, or deposit account is associated with your Card. If a Card holder's purchase exceeds the amount of that Gift Card's or Voucher's balance, the Card holder must pay the difference by another means. Unused Gift Card balances are not transferable. Card is void if copied, altered, transferred, purchased or sold. Purchases of Cards are final and not refundable. We reserve the right to correct the balance of a Gift Card if we believe that a billing error has occurred, and we disclaim all liability for any such billing errors. Cards and their use are subject to this Agreement (including the Privacy Policy) and use of a Card constitutes acceptance thereof. Applicable terms and conditions are subject to change without notice. If the laws pertaining to this Card require additional or different terms or conditions, then such terms and conditions shall apply. For questions or additional information, contact us at projectbuddyservices.com/help.
e. Unused Gift Cards. Gift Cards have no cash value and are not redeemable for cash except in the following ten U.S. states where it is required by law to the extent noted below. If you are a resident of one of these U.S. states, and the balance on your Gift Card is less than the respective dollar amount below, you may redeem it for cash:
• California ≤ \$10
• Montana ≤ \$5
• Washington ≤ \$5
• Vermont ≤ \$1
• Maine ≤ \$5
• New Jersey ≤ \$5
• Rhode Island ≤ \$1
• West Virginia ≤ \$1
• Colorado ≤ \$5
• Massachusetts ≤ \$5
• Oregon ≤ \$5
Simply send your Gift Card along with a self-addressed envelope to us at the address set forth in Section 22 below, Attention: Gift Cards. We'll verify your address, confirm that your Gift Card balance qualifies you for redemption, and send you a check for the exact amount. If your Gift Card balance is equal to or greater than the cap, or we can't verify your residency, we'll return your Gift Card in the envelope provided. We will be unable to redeem or return your Gift Card without a self-addressed envelope and are not responsible for mail that doesn't arrive at the address provided. We cannot guarantee delivery in any way after submittal to the US Postal Service.
10. Intellec                                                                 
                                                                                           
tual Property Rights. The Project Buddy Platform, and the information, data, content and materials, which it contains ("Project Buddy Materials"), are the property of Project Buddy and/or its affiliates and licensors, excluding User-generated content, which Project Buddy has a right to use as described below. The Project Buddy Materials are protected from unauthorized copying and dissemination by United States copyright law, trademark law, international conventions, and other intellectual property laws. Project Buddy and/or its affiliates and licensors are and shall continue to be the sole and exclusive owner of all right, title and interest in and to all intellectual property rights associated with the Project Buddy Materials. Any use of Project Buddy Materials, other than as expressly permitted herein, is prohibited without the prior permission of Project Buddy and/or the relevant right holder. The service marks and trademarks of Project Buddy, including without limitation projectbuddyservices.com and the Project Buddy logo are service marks owned by Project Buddy. Any other trademarks, service marks, logos and/or trade names appearing on the Project Buddy Platform are the property of their respective owners. You may not copy or use any of the marks, logos or trade names appearing on the Project Buddy Platform without the express prior written consent of the owner.
11. Copyright Complaints and Copyright Agent. Project Buddy respects the intellectual property of others, and expects Users to do the same. Project Buddy will respond to properly submitted notices of alleged copyright infringement that comply with applicable law. In the event that a person or entity has a good faith belief that any materials provided on or in connection with the Project Buddy Platform infringe upon that person's or entity's copyright or other intellectual property right (such person or entity, a "Complainant") and sends to Project Buddy a properly submitted copyright notice as indicated below, Project Buddy will investigate, and if it determines, in its discretion, that the material is infringing, Project Buddy will remove the content and may terminate the access of the User who posted such content to the Project Buddy Platform in the case of repeat infringers. All notices claiming an infringement of copyright rights must contain the following:
(i) Identification of the intellectual property right that is allegedly infringed. All relevant registration numbers, or a statement concerning the Complainant's ownership of the work, should be included.
(ii) A statement specifically identifying the location of the infringing material, with enough detail that Project Buddy may find it on the Project Buddy Platform. Please note: it is not sufficient to merely provide a top level URL.
(iii) The complete name, address, telephone number and e-mail address of Complainant.
(iv) A statement that Complainant has a good faith belief that the use of the allegedly infringing material is not authorized by the owner of the rights, or its agents, or by law.
(v) A statement that the information contained in the notification is accurate, and under the penalty of perjury, Complainant is authorized to act on behalf of the owner of the copyright or other property rights that are allegedly infringed;
(vi) A physical or electronic signature of a person authorized to act on behalf of the owner of the intellectual property rights that are allegedly being infringed.
PB's contact information for notice of alleged copyright infringement is:
Email: legal@projectbudyyservices.com
Or via Mail:
Attn: Copyright Agent
PGN Design Group, Inc. d/b/a Project Buddy services
11424 Victoria Ave
Los Angeles, CA 90066
12. The App / Mobile Devices
a. The Project Buddy Platform may allow you to access our services, download our Apps, upload content to the Project Buddy Platform, and receive messages on your mobile device (collectively "Mobile Features"). Your mobile device carrier may prohibit or restrict certain Mobile Features and certain Mobile Features may be incompatible with your mobile device carrier or mobile device. In addition, your mobile device carrier may charge you for standard messaging, data, and other fees to participate in Mobile Features. We have no responsibility or liability for any fees or charges you incur when using the Mobile Features. You should check with your mobile device carrier to find out whether any fees or charges will apply, what plans are available and how much they cost. You should also contact your mobile device carrier with any other questions regarding these issues.
b. You acknowledge that your use of the Apps is subject to any terms set forth in the terms of service of the third party providing the mobile device on which the App operates (e.g., Apple iOS or Android).
c. Project Buddy is not liable if you do not have a compatible mobile device or if you download the wrong version of an App for your mobile device. Project Buddy reserves the right to terminate the use of the Apps or any other aspect of the Project Buddy Platform should you be using the Apps or the Project Buddy Platform with an incompatible or unauthorized device.
d. App Store Sourced Application.
(i) With respect to Apps accessed through or downloaded from the Apple App Store ("App Store Sourced Application"), you will use the App Store Sourced Application only: (i) on an Apple-branded product that runs iOS (Apple's proprietary operating system software); and (ii) as permitted by the "Usage Rules" set forth in the Apple App Store Terms of Service. Project Buddy reserves all rights in and to the Apps not expressly granted to you under this Agreement.
(ii) You acknowledge and agree that (i) this Agreement is valid between you and Project Buddy only, and, that Apple is not a party to this Agreement other than as third-party beneficiary as contemplated below, and (ii) Project Buddy, not Apple, is solely responsible for the App Store Sourced Application and the Project Buddy Platform Content.
(iii) You acknowledge that Apple has no obligation whatsoever to furnish any maintenance or support services to you with respect to the App Store Sourced Application.
(iv) To the maximum extent permitted by applicable law, Apple will have no warranty obligation whatsoever with respect to the App Store Sourced Application.
(v) Notwithstanding anything to the contrary herein, and subject to the terms in this Agreement, you acknowledge that, solely as between Apple and Project Buddy, Project Buddy and not Apple is responsible for addressing any claims you may have relating to the App Store Sourced Application, or your possession and/or use thereof, including, but not limited, to: (i) product liability claims, (ii) any claim that the App Store Sourced Application fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation.
(vi) Further, you agree that if the App Store Sourced Application, or your possession and use of the App Store Sourced Application, infringes on a third party's intellectual property rights, you will not hold Apple responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claims.
(vii) You acknowledge and agree that Apple, and Apple's subsidiaries, are third-party beneficiaries of this Agreement for App Store Sourced Applications, and that, upon your acceptance of the terms and conditions of this Agreement, Apple will have the right (and will be deemed to have accepted the right) to enforce this Agreement for App Store Sourced Applications against you as a third-party beneficiary thereof.
(viii) Without limiting any provisions of this Agreement, you must comply with all applicable third party terms of agreement when using the App Store Sourced Application.
13. Modifications to the Project Buddy Platform. We reserve the right in our sole discretion to review, improve, modify or discontinue, temporarily or permanently, the Project Buddy Platform or any content or information on the Project Buddy Platform with or without notice. We will not be liable to any party for any modification or discontinuance of the Project Buddy Platform.
14. Confidentiality. The term "Confidential Information" shall mean any and all of PB's trade secrets, confidential and proprietary information, personal information and all other information and data of Project Buddy that is not generally known to the public or other third parties who could derive value, economic or otherwise, from its use or disclosure. The Project Buddy Platform contains secured components that are accessible only to those who have been granted a user name and password by Project Buddy. Information contained within the secure components of the Project Buddy Platform is confidential and proprietary. You acknowledge that Confidential Information (as hereinafter defined) is a valuable, special and unique asset of Project Buddy and agree that you will not use Confidential Information other than as necessary for you to make use of the Project Buddy Platform as expressly permitted by this Agreement and only during the term of this Agreement.
15. Disclaimer of Warranties; Limitation on Liability.
a. USE OF THE PROJECT BUDDY PLATFORM IS ENTIRELY AT YOUR OWN RISK. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE PROJECT BUDDY PLATFORM IS PROVIDED ON AN "AS IS" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. WITHOUT LIMITING THE FOREGOING, NEITHER PROJECT BUDDY NOR ITS AFFILIATES OR LICENSORS WARRANT THAT THE PROJECT BUDDY PLATFORM WILL BE UNINTERRUPTED OR ERROR-FREE; NOR DO THEY MAKE ANY WARRANTY AS TO ANY CONTENT AVAILABLE IN OR THROUGH THE HANDY PLATFORM; NOR DO THEY MAKE ANY WARRANTY AS TO ANY PROFESSIONAL'S REGISTRATION, PROFESSIONAL ACCREDITATION OR LICENSE; NOR DO THEY MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE PROJECT BUDDY PLATFORM, OR AS TO THE TIMELINESS, ACCURACY, RELIABILITY, QUALITY, SUITABILITY, SAFETY, COMPLETENESS OR CONTENT OF THE SERVICES, PROFESSIONAL SERVICES, OR ANY PRODUCTS, MERCHANDISE, CONTENT, INFORMATION OR MATERIALS PROVIDED THROUGH OR IN CONNECTION WITH THE USE OF THE PROJECT BUDDY PLATFORM OR THIS AGREEMENT. ACCESS TO THE PROJECT BUDDY PLATFORM IS PROVIDED FREE OF CHARGE AS A COURTESY. NEITHER PROJECT BUDDY NOR ITS AFFILIATES OR LICENSORS ARE RESPONSIBLE FOR THE CONDUCT, WHETHER ONLINE OR OFFLINE, OF ANY USER OF THE PROJECT BUDDY PLATFORM (INCLUDING BUT NOT LIMITED TO THE CONDUCT OF ANY REQUESTERS OR PROFESSIONALS). NEITHER PROJECT BUDDY NOR ITS AFFILIATES OR LICENSORS WARRANT THAT THE PROJECT BUDDY PLATFORM IS FREE FROM VIRUSES, WORMS, TROJAN HORSES, OR OTHER HARMFUL COMPONENTS. PROJECT BUDDY AND ITS AFFILIATES AND LICENSORS CANNOT AND DO NOT GUARANTEE THAT ANY INFORMATION, PERSONAL OR OTHERWISE, SUPPLIED BY YOU WILL NOT BE MISAPPROPRIATED, INTERCEPTED, DELETED, DESTROYED OR USED BY OTHERS.
b. NO LIABILITY. YOU AGREE NOT TO HOLD PROJECT BUDDY, ITS AFFILIATES, ITS LICENSORS, OR ANY OF SUCH PARTIES' AGENTS, EMPLOYEES, OFFICERS, DIRECTORS, CORPORATE PARTNERS, OR PARTICIPANTS (COLLECTIVELY,"MEMBERS") LIABLE FOR ANY DAMAGES, EXPENSES, LOSSES, SUITS, CLAIMS, AND/OR CONTROVERSIES (COLLECTIVELY, "LIABILITIES") THAT HAVE ARISEN OR MAY ARISE, WHETHER KNOWN OR UNKNOWN, RELATING TO YOUR USE OF OR INABILITY TO USE THE PROJECT BUDDY PLATFORM, INCLUDING WITHOUT LIMITATION ANY LIABILITIES ARISING IN CONNECTION WITH THE CONDUCT, ACT OR OMISSION OF ANY USER (INCLUDING WITHOUT LIMITATION STALKING, HARASSMENT, ACTS OF PHYSICAL VIOLENCE, AND LOSS OR DESTRUCTION OF PERSONAL PROPERTY), SERVICES, ANY DISPUTE WITH ANY USER, ANY INSTRUCTION, ADVICE, ACT, OR SERVICE PROVIDED BY PROJECT BUDDY OR MEMBERS, AND ANY DESTRUCTION OF YOUR INFORMATION. UNDER NO CIRCUMSTANCES WILL PROJECT BUDDY OR MEMBERS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL OR EXEMPLARY DAMAGES ARISING IN CONNECTION WITH YOUR USE OF OR INABILITY TO USE THE HANDY PLATFORM OR ANY SERVICES OR MERCHANDISE, EVEN IF SUCH PARTIES WERE OR SHOULD HAVE BEEN ADVISED OF THE POSSIBILITY OF THE SAME. HANDY AND MEMBERS DO NOT ACCEPT ANY LIABILITY WITH RESPECT TO THE QUALITY OR FITNESS OF ANY WORK PERFORMED IN CONNECTION WITH THE PROJECT BUDDY PLATFORM, THE PROFESSIONAL SERVICES, THE MERCHANDISE OR THIS AGREEMENT. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN TYPES OF DAMAGES, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. IF, NOTWITHSTANDING THE FOREGOING EXCLUSIONS, IT IS DETERMINED THAT PROJECT BUDDY OR MEMBERS ARE LIABLE FOR DAMAGES, IN NO EVENT WILL THE AGGREGATE LIABILITY, WHETHER ARISING IN CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE, EXCEED THE TOTAL FEES PAID BY YOU TO PROJECT BUDDY DURING THE SIX (6) MONTHS PRIOR TO THE TIME SUCH CLAIM AROSE.
c. RELEASE. PROJECT BUDDY AND MEMBERS EXPRESSLY DISCLAIM ANY LIABILITY THAT MAY ARISE BETWEEN USERS OF THE PROJECT BUDDY PLATFORM. THE PROJECT BUDDY PLATFORM IS ONLY A VENUE FOR CONNECTING USERS. TO THE EXTENT THAT THE PROJECT BUDDY PLATFORM CONNECTS A USER TO A THIRD PARTY PROVIDER FOR THE PURPOSES OF PROVIDING MERCHANDISE HEREUNDER, PROJECT BUDDY WILL NOT BE RESPONSIBLE FOR ASSESSING THE SUITABILITY, LEGALITY OR ABILITY OF ANY THIRD PARTY PROVIDERS AND YOU EXPRESSLY WAIVE AND RELEASE PROJECT BUDDY FROM ANY AND ALL LIABILITY, CLAIMS OR DAMAGES ARISING FROM OR IN ANY WAY RELATED TO THE THIRD PARTY SERVICE PROVIDER. BECAUSE PROJECT BUDDY IS NOT INVOLVED IN THE ACTUAL CONTACT BETWEEN USERS OR IN THE COMPLETION OF ANY PROFESSIONAL SERVICE, IN THE EVENT THAT YOU HAVE A DISPUTE WITH ONE OR MORE USERS, YOU RELEASE PROJECT BUDDY AND MEMBERS FROM ANY AND ALL CLAIMS, DEMANDS, OR DAMAGES (ACTUAL, DIRECT OR CONSEQUENTIAL) OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, SUSPECTED AND UNSUSPECTED, DISCLOSED AND UNDISCLOSED, ARISING OUT OF OR IN ANY WAY CONNECTED WITH SUCH DISPUTE. YOU EXPRESSLY WAIVE AND RELEASE ANY AND ALL RIGHTS AND BENEFITS UNDER SECTION 1542 OF THE CIVIL CODE OF THE STATE OF CALIFORNIA (OR ANY ANALOGOUS LAW OF ANY OTHER STATE), WHICH READS AS FOLLOWS: "A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH, IF KNOWN BY HIM OR HER, MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR."
d. ADDITIONAL DISCLAIMER. THE QUALITY OF THE PROFESSIONAL SERVICES AND/OR THE MERCHANDISE SCHEDULED OR REQUESTED THROUGH THE USE OF THE PROJECT BUDDY PLATFORM IS ENTIRELY THE RESPONSIBILITY OF THE PROFESSIONAL WHO ULTIMATELY PROVIDES SUCH PROFESSIONAL SERVICES TO YOU AND/OR THE THIRD PARTY MERCHANDISE PROVIDER. YOU UNDERSTAND, THEREFORE, THAT BY USING THE PROJECT BUDDY PLATFORM, YOU MAY BE EXPOSED TO PROFESSIONAL SERVICES AND/OR MERCHANDISE THAT ARE POTENTIALLY DANGEROUS, OFFENSIVE, HARMFUL TO MINORS, UNSAFE OR OTHERWISE OBJECTIONABLE, AND THAT YOU USE THE PROJECT BUDDY PLATFORM, AND SUCH PROFESSIONAL, AT YOUR OWN RISK.
NOTHING IN THIS AGREEMENT OR THE PROJECT BUDDY PLATFORM CONSTITUTES, OR IS MEANT TO CONSTITUTE, ADVICE OF ANY KIND. IF YOU REQUIRE ADVICE IN RELATION TO ANY LEGAL, FINANCIAL OR MEDICAL MATTER YOU SHOULD CONSULT AN APPROPRIATE PROFESSIONAL.
BY USING THE PROJECT BUDDY PLATFORM, YOU AGREE THAT THE EXCLUSIONS AND LIMITATIONS OF LIABILITY SET OUT IN THIS AGREEMENT ARE REASONABLE. IF YOU DO NOT BELIEVE THEY ARE REASONABLE, YOU MUST NOT USE THE PROJECT BUDDY PLATFORM.
YOU ACCEPT THAT, AS A CORPORATION, PGN DESIGN GROUP HAS AN INTEREST IN LIMITING THE PERSONAL LIABILITY OF ITS OFFICERS, DIRECTORS AND EMPLOYEES. YOU AGREE THAT YOU WILL NOT BRING ANY CLAIM PERSONALLY AGAINST PGN'S OFFICERS, DIRECTORS OR EMPLOYEES IN CONNECTION WITH ANY DISPUTE, LOSS OR DAMAGE. WITHOUT PREJUDICE TO THE FOREGOING, YOU AGREE THAT THE LIMITATIONS OF WARRANTIES AND LIABILITY SET OUT IN THIS AGREEMENT WILL PROTECT THE PGN OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, LICENSORS, PARENTS, SUBSIDIARIES, AFFILIATES, SUCCESSORS, ASSIGNS AND SUB-CONTRACTORS AS WELL AS PROJECT BUDDY.
EACH PARTY ACKNOWLEDGES THAT THE OTHER PARTY HAS ENTERED INTO THIS AGREEMENT RELYING ON THE LIMITATIONS OF LIABILITY STATED HEREIN AND THAT THOSE LIMITATIONS ARE AN ESSENTIAL BASIS OF THE BARGAIN BETWEEN THE PARTIES.
16. Indemnification. You hereby agree to indemnify, defend, and hold harmless Project Buddy, its licensors, and each such party's directors, officers, parent organizations, subsidiaries, affiliates, members, employees, agents, attorneys, independent contractors and vendors from and against any and all claims, losses, expenses, liabilities, damages or demands (including attorneys' fees and costs incurred), in connection with or resulting from, directly or indirectly: (i) your use or misuse of or inability to use the Handy Platform, any Merchandise and/or any Professional Service, (ii) your violation of this Agreement, (iii) your violation of any applicable law or regulation; (iv) your violation of the rights of another (including but not limited to Professionals), and (v) Your Information and content that you submit or transmit through the Project Buddy Platform. Project Buddy reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to your indemnification. You will not, in any event, settle any such claim or matter without the prior written consent of Project Buddy.
17. Mutual Arbitration Agreement.
a. Informal Negotiations. To expedite resolution and reduce the cost of any dispute, controversy or claim, past, present, or future, between you and Project Buddy, including without limitation any dispute or claim related to or arising out of this Agreement ("Dispute"), you and Project Buddy may attempt to negotiate any Dispute informally (the "Informal Negotiations") before initiating any arbitration or court proceeding. Such Informal Negotiations will commence upon written notice. Your address for any notices under this Section 17 is your email address and/or physical address that you have provided to Project Buddy. PB's address for such notices is: legal@projectbuddyservices.com and/or by mail to PGN Design Group, llc., Attn: Legal, 11424 Victoria Ave, Los Angeles, CA 90066.
b. Arbitration. If a Dispute is not resolved through Informal Negotiations, you and Project Buddy agree to resolve any and all Disputes (except those Disputes expressly excluded below) through final and binding arbitration ("Arbitration Agreement"). This Arbitration Agreement shall be governed by the Federal Arbitration Act and evidences a transaction involving commerce. The arbitration will be commenced and conducted before a single arbitrator under the Commercial Arbitration Rules (the "AAA Rules") of the American Arbitration Association ("AAA") and, where appropriate, the AAA's Supplementary Procedures for Consumer Related Disputes ("AAA Consumer Rules"), both of which are available at the AAA website (www.adr.org). Your arbitration fees and your share of arbitrator compensation will be governed by the AAA Rules (and, where appropriate, limited by the AAA Consumer Rules). If you are unable to pay such costs, Project Buddy will pay all arbitration fees and expenses. Each party will pay the fees for his/her or its own attorneys, subject to any remedies to which that party may later be entitled under applicable law. The arbitrator will make a decision in writing. Additionally, the arbitrator, and not any federal, state, or local court or agency, shall have the exclusive authority to resolve any dispute relating to the interpretation, applicability, enforceability, or formation of this Arbitration Agreement. However, the preceding sentence shall not apply to the "Class Action Waiver" described in Section d below.
c. Excluded Disputes. You and Project Buddy agree that the following Disputes are excluded from this Arbitration Agreement: (1) any Dispute seeking to enforce or protect, or concerning the validity of, any of your or our intellectual property rights; (2) individual claims in small claims court; (3) any claim that an applicable federal statute expressly states cannot be arbitrated; and (4) any claim for injunctive relief.
d. WAIVER OF RIGHT TO BE A PLAINTIFF OR CLASS MEMBER IN A CLASS ACTION.
You and Project Buddy agree to bring any Dispute in arbitration on an individual basis only, and not as a class or collective action. There will be no right or authority for any Dispute to be brought, heard or arbitrated as a class or collective action ("Class Action Waiver"). Regardless of anything else in this Arbitration Agreement and/or the applicable AAA Rules or AAA Consumer Rules, the interpretation, applicability, enforceability or formation of the Class Action Waiver may only be determined by a court and not an arbitrator.
e. Rules/Standards Governing Arbitration Proceeding. A party who wishes to arbitrate a Dispute covered by this Arbitration Agreement must initiate an arbitration proceeding no later than the expiration of the statute of limitations that applicable law prescribes for the claim asserted. The arbitrator shall apply the statute of limitations that would have applied if the Dispute had been brought in court. The arbitrator may award any remedy to which a party is entitled under applicable law, but remedies shall be limited to those that would be available to a party in their individual capacity, and no remedies that otherwise would be available to an individual under applicable law will be forfeited. The arbitrator is without authority to apply any different substantive law. The parties have the right to conduct adequate civil discovery and present witnesses and evidence as needed to present their cases and defenses, and any dispute in this regard shall be decided by the arbitrator. The location of the arbitration proceeding shall take place in the city or county where you reside, unless each party agrees otherwise. A court of competent jurisdiction shall have the authority to enter judgment upon the arbitrator's decision/award.
f. Severability. You and Project Buddy agree that if any portion of this section entitled "Mutual Arbitration Agreement" is found illegal or unenforceable, that portion will be severed and the remainder of this section 17 will be given full force and effect.
18. Governing Law; Jurisdiction. Except for the Arbitration Agreement in Section 17, which is governed by the Federal Arbitration Act, this Agreement is governed and interpreted pursuant to the laws of the State of California, United States of America, notwithstanding any principles of conflicts of law. For all Disputes not subject to arbitration, You agree to submit to the personal and exclusive jurisdiction and venue of the courts located within the county of Los Angeles, California.
19. Assignment. This Agreement may not be assigned or transferred by you without our prior written approval. We may assign or transfer this Agreement without your consent, including but not limited to assignments: (i) to a parent or subsidiary, (ii) to an acquirer of assets, or (iii) to any other successor or acquirer. Any assignment in violation of this section shall be null and void. This Agreement shall inure to the benefit of permitted successors and assigns.
20. General Provisions. No agency, partnership, joint venture, employer-employee or franchiser-franchisee relationship is intended or created by this Agreement. A failure by us to enforce any provision(s) of this Agreement will not be construed as a waiver of any provision or right. This Agreement constitutes the entire agreement between you and Project Buddy with respect to its subject matter. If any provision of this Agreement is found to be invalid or unenforceable, the remaining provisions will be enforced to the fullest extent possible, and the remaining provisions will remain in full force and effect. You agree that, except as otherwise expressly provided in this Agreement, there shall be no third party beneficiaries to this Agreement. You agree that regardless of any statute or law to the contrary, any Dispute, claim or cause of action arising out of or related to this Agreement must be filed within one (1) year after such Dispute, claim or cause of action arose or be forever barred. All notices provided by a party in connection with this Agreement will be deemed given as of the day they are received either by email, messenger, delivery service, or in the U.S. Mail, postage prepaid, certified or registered, return receipt requested, and addressed as follows: Your address for such notices is your email address and/or physical address that you have provided to Project Buddy. PB's address for such notices is: legal@projectbuddyservices.com and/or by mail to PGN Design Group, llc, Attn: Legal, 11424 Victoria Ave, Los Angeles, CA 90066. The captions in this Agreement are solely for convenience and shall not affect the interpretation of this Agreement. This Agreement shall not be modified except in writing signed by both parties or by means of a new posting by Project Buddy, as described below. This Agreement shall be interpreted as if jointly drafted by the parties. Project Buddy shall have no liability to you for any failure or delay in performing its obligations in this Agreement where such failure or delay is caused by an event or circumstance beyond PB's reasonable control including, without limitation, strikes, lock-outs and other industrial disputes, breakdown of systems or network access, failure of Professionals to perform, flood, fire, explosion, acts of terrorism or accident.
21. Changes to this Agreement. We reserve the right, at our sole and absolute discretion, to change, modify, add to, supplement or delete any of the terms and conditions of this Agreement at any time, effective with or without prior notice. If any future changes to this Agreement are unacceptable to you or cause you to no longer be in compliance with this Agreement, you must terminate, and immediately stop using, the Project Buddy Platform. Your continued use of the Project Buddy Platform following any revision to this Agreement constitutes your complete and irrevocable acceptance of any and all such changes.
22. Contact Information. If you have any questions regarding this Agreement, please contact us at legal@projectbuddyservices.com or by mail at:
Project Buddy LLC
Attn.: Legal
375 Dalkeith Ave
Los Angeles, CA 90049
I HEREBY ACKNOWLEDGE THAT I HAVE READ AND UNDERSTAND THESE TERMS OF USE AND PRIVACY POLICY, AND AGREE THAT MY USE OF THE PROJECT BUDDY PLATFORM IS AN ACKNOWLEDGMENT OF MY AGREEMENT TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT.
Last updated: January 2, 2021''';
}
